import type { Metadata } from "next";
import NextAuthProvider from "@/components/providers/NextAuthProvider";
import "./globals.css";
import { poppins } from "./ui/fonts";
import ReduxProvider from "@/components/providers/ReduxProvider";

export const metadata: Metadata = {
  title: "Gateway",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} font-sans `}>
        <NextAuthProvider>
          <ReduxProvider>
            <main>{children}</main>
          </ReduxProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
