import type { Metadata } from "next";
import NextAuthProvider from "@/components/providers/NextAuthProvider";
import "./globals.css";
import { poppins } from "./ui/fonts";
import ReduxProvider from "@/components/providers/ReduxProvider";
import { NotificationProvider } from "@/components/providers/NotificationProvider";

export const metadata: Metadata = {
  title: "Gateway",
  description: "Generated by create next app",
};

export default function RootLayout({
  // ← no longer async
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} font-sans`}>
        <NextAuthProvider>
          <ReduxProvider>
            <NotificationProvider>
              {" "}
              {/* ← no prop */}
              <main>{children}</main>
            </NotificationProvider>
          </ReduxProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
