import type { Metadata } from "next";
import NextAuthProvider from "@/components/providers/NextAuthProvider";
import "./globals.css";
import { poppins } from "./ui/fonts";
import ReduxProvider from "@/components/providers/ReduxProvider";
import { NotificationProvider } from "@/components/providers/NotificationProvider";
import fetcher from "@/helper/fetcher";
import { URLS } from "@/constants";

export const metadata: Metadata = {
  title: "Gateway",
  description: "Generated by create next app",
};
interface Data {
  title: string;
  body: string;
  data: object;
  is_read: boolean;
  created_at: string;
}
interface RES {
  data: Data[];
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let notifications = [];
  try {
    const res = await fetcher<RES>(URLS.GET_NOTIFICATION);
    console.log(res);
    notifications = res.data ?? [];
  } catch (e) {
    console.error("Failed to fetch notifications:", e);
  }

  return (
    <html lang="en">
      <body className={`${poppins.variable} font-sans`}>
        <NextAuthProvider>
          <ReduxProvider>
            <NotificationProvider initialNotifications={notifications}>
              <main>{children}</main>
            </NotificationProvider>
          </ReduxProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
